#!/bin/bash

set -e -u

cd "$(dirname $0)/.."

rm -rf out
mkdir out

echo "--- Building jj CLI (on Node.js) ---"
clojure -A:cljs -m cljs.main -t node -O advanced -o out/jj -c com.rentpath.jj.cli
chmod a+x out/jj
echo "--- Finished building jj CLI (on Node.js) ---"
