#!/bin/bash

set -e -u

cd "$(dirname $0)/.."

echo "--- Building jj REPL uberjar ---"
# lein with-profile +uberjar-repl uberjar
echo "Setting up directories..."
rm -rf target/custom
mkdir -p target/custom/classes
echo "Unpacking dependency JARs..."
for jar in `clojure -A:clj:uberjar -Spath | awk 'BEGIN { RS = ":" } /\.jar/ { print $0 }'`
do
    unzip -uoq $jar -d target/custom/classes
done

echo "Copying local directories on classpath..."
for dir in `clojure -A:clj:uberjar -Spath | awk 'BEGIN { RS = ":" } /target\/custom/ { next } /^\s*[^\/]/ { print $0 }'`
do
    cp -f -R $dir target/custom/classes/
done

echo "Compiling main Clojure namespace to a Java class..."
clojure -A:clj:uberjar -e "(binding [*compile-path* \"target/custom/classes\"] (compile 'com.rentpath.jj.repl))"

echo "Creating executable JAR file..."
cd target/custom/classes
jar cvfe ../jj-repl.jar com.rentpath.jj.repl * > /dev/null
cd ../../..
echo "--- Finished building jj REPL uberjar ---"
